// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Untiled2D
{
    public class MapObject
    {
        public string name { get; private set; }

        public MapObject (string name)
        {   
            this.name = name;
        }
         
    }
}

